CREATE DATABASE FLICKERPALACE

USE FLICKERPALACE

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(50),
	NGAYSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	DIENTHOAI VARCHAR(20),
	DIACHI VARCHAR(50),
	TAIKHOAN VARCHAR(50),
	MATKHAU VARCHAR(20)
)

CREATE TABLE QLKHACHHANG
(
	MAQLKH VARCHAR(5) PRIMARY KEY,
	MANV VARCHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MAKH VARCHAR(5) FOREIGN KEY REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE PHIM 
(
	MAPHIM VARCHAR(5) PRIMARY KEY,
	TENPHIM VARCHAR(50),
	NAMSX INT,
	THELOAI VARCHAR(20),
	THOILUONG VARCHAR(10)
)

ALTER TABLE PHIM ADD DIENVIEN VARCHAR(50)
ALTER TABLE PHIM ADD DAODIEN VARCHAR(50)
ALTER TABLE PHIM ADD AGELIMIT VARCHAR(5)
ALTER TABLE PHIM ALTER COLUMN THELOAI VARCHAR(100)
ALTER TABLE PHIM ALTER COLUMN THOILUONG INT
ALTER TABLE PHIM ALTER COLUMN AGELIMIT TINYINT
ALTER TABLE PHIM ALTER COLUMN DIENVIEN VARCHAR(100)

CREATE TABLE QLPHIM 
(
	MAQLPHIM VARCHAR(5) PRIMARY KEY,
	MANV VARCHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MAPHIM VARCHAR(5) FOREIGN KEY REFERENCES PHIM(MAPHIM)
)

CREATE TABLE PHONG
(
	MAPHONG VARCHAR(5) PRIMARY KEY,
	TENPHONG VARCHAR(20),
	SOGHE TINYINT
)

CREATE TABLE LICHCHIEU
(
	MALC VARCHAR(5) PRIMARY KEY,
	MAPHIM VARCHAR(5) FOREIGN KEY REFERENCES PHIM(MAPHIM),
	MAPHONG VARCHAR(5) FOREIGN KEY REFERENCES PHONG(MAPHONG),
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME
)

ALTER TABLE LICHCHIEU ADD MARAP VARCHAR(5)
ALTER TABLE LICHCHIEU ADD CONSTRAINT FK_MARAP FOREIGN KEY (MARAP) REFERENCES RAP(MARAP)
ALTER TABLE LICHCHIEU ADD SUATCHIEU VARCHAR(10)


CREATE TABLE VE 
(
	MAVE VARCHAR(5) PRIMARY KEY,
	MAKH VARCHAR(5) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MALC VARCHAR(5) FOREIGN KEY REFERENCES LICHCHIEU(MALC),
	NGAYMUA SMALLDATETIME,
	LOAIVE VARCHAR(10),
	GIATIEN INT
)

CREATE TABLE GHENGOI
(
	MAGHE VARCHAR(5) PRIMARY KEY,
	MAPHONG VARCHAR(5) FOREIGN KEY REFERENCES PHONG(MAPHONG)
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(40),
	TAIKHOAN VARCHAR(50),
	MATKHAU VARCHAR(20)
)

CREATE TABLE RAP
(
	MARAP VARCHAR(5) PRIMARY KEY,
	TENRAP VARCHAR(50),
	THANHPHO VARCHAR(20)
)